export type Project = {
  id: number;
  title: string;
  category: string;
  videoUrl: string;
  image: string;
  span: string;
  featured?: boolean;
};

const preview = (id: string) => `https://drive.google.com/file/d/${id}/preview`;

export const projects: Project[] = [
  {
    id: 1,
    title: "Therap Car Race Game",
    category: "Interactive Game",
    videoUrl: preview("1Wv_qb6v8FeW33l187aNb-fnTwJgo7NDX"),
    image: "/images/therap-car-race.jpg",
    span: "md:col-span-7",
    featured: true,
  },
  {
    id: 2,
    title: "Flappy Bird",
    category: "Mobile Game",
    videoUrl: preview("1taM7Lu-Eb8ZL_LK06r8MbD3TmMtjGK0k"),
    image: "/images/flappy-bird.jpg",
    span: "md:col-span-5",
    featured: true,
  },
  {
    id: 3,
    title: "VR Milky Bar Journey",
    category: "VR Experience",
    videoUrl: preview("12OKb7VGzBNXKIj80msttuERIR2qQ3hPl"),
    image: "/images/vr-milky-bar.jpg",
    span: "md:col-span-5",
    featured: true,
  },
  {
    id: 4,
    title: "Mixed Reality VR Experience - Operation Theatre",
    category: "Mixed Reality",
    videoUrl: preview("1wS1JE_kwZGKqvcCz4dsbqmDnEQs26AgB"),
    image: "/images/operation-theatre-mr.jpg",
    span: "md:col-span-7",
    featured: true,
  },
  {
    id: 5,
    title: "Bellissimo Motion Game Solution",
    category: "Motion Game",
    videoUrl: preview("1Bgv_yaOCGhLs5Ze1VbfIdlu_TfyH8zW_"),
    image: "/images/bellissimo.jpg",
    span: "md:col-span-7",
    featured: true,
  },
  {
    id: 6,
    title: "Penalty Shoot - Mobile",
    category: "Mobile Game",
    videoUrl: preview("1NUYxlE4L02D7Zdp8LjIQnxri1TvQw_iS"),
    image: "/images/penalty-shoot.jpg",
    span: "md:col-span-5",
    featured: true,
  },
  {
    id: 7,
    title: "Boo Bear",
    category: "Interactive / Game",
    videoUrl: preview("1ZihKI5p_wtyKlQta0e0J_nHspng8eORE"),
    image: "/images/boo-bear.jpg",
    span: "md:col-span-5",
    featured: true,
  },
  {
    id: 8,
    title: "TiKA AR Mural",
    category: "AR Experience",
    videoUrl: preview("1Fk0BnCil16aSUvLzZFReekm1k2wdHQ9J"),
    image: "/images/tika-ar-mural.jpg",
    span: "md:col-span-7",
    featured: true,
  },
  {
    id: 9,
    title: "bKash Offer Catcher",
    category: "AR Experience",
    videoUrl: preview("1jlAZbn1D6HB4LLiPx_IsU21AO4CVmpRG"),
    image: "/images/bkash-offer-catcher.jpg",
    span: "md:col-span-5",
  },
  {
    id: 10,
    title: "Nisa Card - Rotoscope",
    category: "Motion Film",
    videoUrl: preview("14nzIqCOcHwcXHL5DExaVQkG64oRZbDYi"),
    image: "/images/nisa-card-rotoscope.jpg",
    span: "md:col-span-7",
  },
  {
    id: 11,
    title: "Motion Tracking Brush System",
    category: "Motion Game",
    videoUrl: preview("11HnStMhwJeMdiSL2F3MB-PFcwbC0B_uU"),
    image: "/images/motion-tracking-brush.jpg",
    span: "md:col-span-7",
  },
  {
    id: 12,
    title: "Interactive Book Projection",
    category: "Interactive",
    videoUrl: preview("1mIRPQ5y69R_rMDHaiB3bJ6nHf7h7V6dk"),
    image: "/images/interactive-book.jpg",
    span: "md:col-span-5",
  },
  {
    id: 13,
    title: "Robi Next-Gen AR Photo booth",
    category: "AR Experience",
    videoUrl: preview("1bfQZRTeYwE8PzOtoSfhHEWXIhIDpNtZg"),
    image: "/images/robi-ar-photobooth.jpg",
    span: "md:col-span-5",
  },
  {
    id: 14,
    title: "Bondstein VR Motorbike Experience",
    category: "VR Experience",
    videoUrl: preview("1BlfmPrXZerVrWhARyeA_LRNqo9kixk2e"),
    image: "/images/bondstein-vr-motorbike.jpg",
    span: "md:col-span-7",
  },
  {
    id: 15,
    title: "DBL - Photo with Shakib",
    category: "AR Experience",
    videoUrl: preview("1MsQwtmAFlkc9UWk-6Va8hF8yyhyv0lg8"),
    image: "/images/dbl-photo-shakib.jpg",
    span: "md:col-span-5",
  },
  {
    id: 16,
    title: "Maggi VR Beat Saber",
    category: "VR Game",
    videoUrl: preview("1DpyyupFnhiCHTixFlK88TifkG2FsTuXe"),
    image: "/images/maggi-vr-beat-saber.jpg",
    span: "md:col-span-7",
  },
  {
    id: 17,
    title: "VR Smart Bangladesh",
    category: "VR Experience",
    videoUrl: preview("1bzAzUUK9npNhH3FKSVjnWSrRLBgBHYQ2"),
    image: "/images/vr-smart-bangladesh.jpg",
    span: "md:col-span-7",
  },
  {
    id: 18,
    title: "Kinect Coloring",
    category: "Motion Game",
    videoUrl: preview("1njIgwY8K2FzIAJgHJhYo17P3sjJguClx"),
    image: "/images/kinect-coloring.jpg",
    span: "md:col-span-5",
  },
  {
    id: 19,
    title: "Interactive Wall",
    category: "Interactive",
    videoUrl: preview("1dcYLeLXqoiucO_0ASqx2PH-Y9w4WuVSc"),
    image: "/images/interactive-wall.jpg",
    span: "md:col-span-7",
  },
  {
    id: 20,
    title: "Q/A Spaceship Game",
    category: "Interactive Game",
    videoUrl: preview("1yaaZwZjwbTgDQS3LBlZ7kZ8e10kngUuq"),
    image: "/images/qa-spaceship.jpg",
    span: "md:col-span-5",
  },
  {
    id: 21,
    title: "Marker based interactive AV Zone",
    category: "AR Experience",
    videoUrl: preview("1Xw-QPeb_YlFXAwGTyNSxt8X9KjIGhRPh"),
    image: "/images/marker-av-zone.jpg",
    span: "md:col-span-5",
  },
  {
    id: 22,
    title: "Motion detection AV Player",
    category: "Motion",
    videoUrl: preview("1OUNhBtQSaPzfBl1h9fBe5R4XtV2FdXjQ"),
    image: "/images/motion-av-player.jpg",
    span: "md:col-span-7",
  },
  {
    id: 23,
    title: "HMO Holographic 3D intro",
    category: "Holographic",
    videoUrl: preview("1LM211EzAgyZE6B8do_or44a-aD-0sFam"),
    image: "/images/hmo-holographic-intro.jpg",
    span: "md:col-span-7",
  },
  {
    id: 24,
    title: "HMO Q/A Buzzer",
    category: "Interactive",
    videoUrl: preview("12sGbOcPXd10NRHEUffeNDxhWAL1-65SX"),
    image: "/images/hmo-qa-buzzer.jpg",
    span: "md:col-span-5",
  },
  {
    id: 25,
    title: "Trivia",
    category: "Interactive Game",
    videoUrl: preview("1VEiqEuhNbAwezVcRfhK3dL-g3ugHWLHl"),
    image: "/images/trivia.jpg",
    span: "md:col-span-5",
  },
  {
    id: 26,
    title: "Therap24 interactive signature wall",
    category: "Interactive",
    videoUrl: preview("1lCIxQWB060X7zrbzsFOsZFHIj1OldpxB"),
    image: "/images/therap24-signature-wall.jpg",
    span: "md:col-span-7",
  },
  {
    id: 27,
    title: "Therap AR 360 Photobooth",
    category: "AR Experience",
    videoUrl: preview("12AC8edvhnq8537_zI_06iR0nUMZgi7f5"),
    image: "/images/therap-ar-360-photobooth.jpg",
    span: "md:col-span-5",
  },
  {
    id: 28,
    title: "MEDX bubble shooting game",
    category: "Interactive Game",
    videoUrl: preview("1jAhWAy0VyIKZqu4s8cYlbeXzCcAXvraW"),
    image: "/images/medx-bubble-shooting.jpg",
    span: "md:col-span-7",
  },
  {
    id: 29,
    title: "3D Projection room",
    category: "Projection",
    videoUrl: preview("1_xS8KMok7h-mROx9aAvFT3KZ6HiAK_yf"),
    image: "/images/projection-room-3d.jpg",
    span: "md:col-span-7",
  },
  {
    id: 30,
    title: "Kitkat Hall of Fame",
    category: "Interactive",
    videoUrl: preview("1m0EIQFwSVT6uHb8G1h0guKLxDBzFUAbt"),
    image: "/images/kitkat-hall-of-fame.jpg",
    span: "md:col-span-5",
  },
  {
    id: 31,
    title: "Stomach story",
    category: "Interactive",
    videoUrl: preview("15zlsmpFy0-Ay0KS7Zj5Vz0azuEZhuObp"),
    image: "/images/stomach-story.jpg",
    span: "md:col-span-5",
  },
  {
    id: 32,
    title: "AR Projection Flipbook",
    category: "AR Experience",
    videoUrl: preview("1araoeYV7pR63TJK15Hrhgllsnmmyf_v_"),
    image: "/images/ar-projection-flipbook.jpg",
    span: "md:col-span-7",
  },
  {
    id: 33,
    title: "Immunity catcher game",
    category: "Interactive Game",
    videoUrl: preview("1JSwDVCnea9Fb_wFiL2xc4snRsklSXrIN"),
    image: "/images/immunity-catcher.jpg",
    span: "md:col-span-5",
  },
  {
    id: 34,
    title: "MILO Cricket",
    category: "Interactive Game",
    videoUrl: preview("176S3_7GZRTZWkd3_QLtGdxaiNGFyBiTy"),
    image: "/images/milo-cricket.jpg",
    span: "md:col-span-7",
  },
  {
    id: 35,
    title: "Partner VR experience",
    category: "VR Experience",
    videoUrl: preview("1YGGcdVxFaAtzuVardgUtDlxr6Ekvm8nL"),
    image: "/images/partner-vr.jpg",
    span: "md:col-span-7",
  },
  {
    id: 36,
    title: "Lyfe Markerbased catcher game",
    category: "AR Game",
    videoUrl: preview("138AbQZMuSkxQgfwPihMKYcsezj_aRoYn"),
    image: "/images/lyfe-marker-catcher.jpg",
    span: "md:col-span-5",
  },
  {
    id: 37,
    title: "Lifebuoy AR photobooth",
    category: "AR Experience",
    videoUrl: preview("1oce9B7IaGSGX3d7Q65bmms8EdTmt81N8"),
    image: "/images/lifebuoy-ar-photobooth.jpg",
    span: "md:col-span-7",
  },
  {
    id: 38,
    title: "Power 2D Game",
    category: "Interactive Game",
    videoUrl: preview("1WZrQzLDnBaAifOVqmqwVU_V6fhTAfh7a"),
    image: "/images/power-2d-game.jpg",
    span: "md:col-span-5",
  },
  {
    id: 39,
    title: "AR Stall",
    category: "AR Experience",
    videoUrl: preview("1YSVylxYVCFb2q3BQ7CRKtoDPUU9y-bo8"),
    image: "/images/ar-stall.jpg",
    span: "md:col-span-5",
  },
];

export const explorations = [
  { src: "/images/explore-01.jpg", projectId: 1, alt: "Night race through a neon city" },
  { src: "/images/explore-02.jpg", projectId: 2, alt: "Skyward mobile bird study" },
  { src: "/images/explore-03.jpg", projectId: 3, alt: "Chocolate world environment" },
  { src: "/images/explore-04.jpg", projectId: 4, alt: "Holographic anatomy theatre" },
  { src: "/images/explore-05.jpg", projectId: 5, alt: "Motion game installation" },
  { src: "/images/explore-06.jpg", projectId: 6, alt: "Penalty strike freeze-frame" },
  { src: "/images/explore-07.jpg", projectId: 7, alt: "Boo Bear character study" },
  { src: "/images/explore-08.jpg", projectId: 8, alt: "AR mural lifting off a wall" },
];

export const journal = [
  {
    index: "01",
    title: "Spatial narrative",
    body: "Stories in VR do not scroll. They surround. We write beats for the body — where you turn, what you reach for, what you dare to approach.",
  },
  {
    index: "02",
    title: "Hands, gaze, presence",
    body: "Interaction is designed for how people actually move. Gaze as invitation, hands as grammar, locomotion as pacing.",
  },
  {
    index: "03",
    title: "Performance as material",
    body: "Ninety frames is not a spec, it is a feeling. Comfort, clarity and brand craft are the same problem.",
  },
  {
    index: "04",
    title: "Brands, made inhabitable",
    body: "From a thirty-second film to a world you can walk through. We turn campaigns into places people remember with their bodies.",
  },
];

export const stats = [
  { value: 30, suffix: "+", label: "Immersive Projects" },
  { value: 15, suffix: "+", label: "Brand Partners" },
  { value: 100, suffix: "%", label: "Client Satisfaction" },
];

export const socials = [
  { label: "Instagram", href: "https://instagram.com/singularityimmersive" },
  { label: "LinkedIn", href: "https://www.linkedin.com/company/singularity-immersive" },
  { label: "X", href: "https://x.com/singularityimmersive" },
];

export const STUDIO_EMAIL = "hello@singularityimmersive.com";
export const ROLES = ["VR", "AR", "Mixed Reality", "Interactive"] as const;
